import = ["/home/alimertturaclar/.config/alacritty/chadracula.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "tmux"

[keyboard]
  [[keyboard.bindings]]
  key = "N"
  mods = "Control|Shift"
  action = "CreateNewWindow"
